config/routes.rb
Rails.application.routes.draw do
  resources :claims
  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	mount_base64_uploader :file, ImageUploader
	belongs_to :claim
end

app/models/claim.rb
class Claim < ApplicationRecord
	has_many :attachments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :claims, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :verify_authenticity_token

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        if params[:file_name] && params[:size] && params[:type] && params[:image_base64]
          file_names = params[:file_name].split("&&&=>")
          file_names.shift
          sizes = params[:size].split("&&&=>")
          sizes.shift
          types = params[:type].split("&&&=>")
          types.shift
          bases = params[:image_base64].split("&&&=>")
          bases.shift 
          bases.each_with_index do |base|
            @claim.attachments.create(:file=> base, :claim_id => @claim.id)
          end
         end
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:user_id, :title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@attachments = Attachment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-warning"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/claims/_form.html.erb
<section class="dashboard my-listings payment-settings tickets-purchase create-listing">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="bhoechie-tab">
          <div class="bhoechie-tab-content active">           
            <h3 class="dashboard-column-title">Create New Claim</h3>
            <p>A fast and easy way to capture your claim photos and documents</p>
            <p>Claim no.: <%= current_user.claims.count + 1 %></p>
            <p><%= current_user.email %></p>
            <div class="contents order-confirmed-right">
              <%= form_with(model: @claim, local: true) do |form| %>
                <% if @claim.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

                    <ul>
                    <% @claim.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= form.hidden_field :user_id, value: current_user.id %>
                <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="Sr730HDVe5GYQn1S5tKyiVOmutbzMBmRa0zY+Pn6qf8="></div> 
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Photo upload/Capture</h3>
                  </div>
                  <div class="panel-body">                  
                    <div class="form-group my-photos clearfix">
                    
                      <output id="result" width="77" height="74"/>
                      <img src="" alt="">
                      <input type="hidden"  style="border:0;" id="file_name" onClick="jQuery('#upload_datafile').click()" readonly="readonly" name="file_name" class="browse"/>

                      <input type="hidden" name="file_name" value="" id="fileDragName">
                      <input type="hidden" name="size" value="" id="fileDragSize">
                      <input type="hidden" name="type" value="" id="fileDragType">
                      <input type="hidden" name="image_base64" value="" id="fileDragData">
                       
                    </div>
                    <span class="uploaded-photo">
                      <a href="#" class="upload-photo" onclick="document.getElementById('files').click()"><i class="fa fa-camera"></i>Upload
                      </a>
                      <%= file_field_tag :avatar, name: "image_attachments[avatar][]", :multiple => true, :class => 'browse', :id=>"files" %>
                    </span>
                    <div class="form-group">
                        <input type="checkbox" name="remember" id="remember" value="1"> I agree the
                        <a href="/terms">Terms and Conditions</a>
                      </div>                  
                    </div>
                    <div class="form-group">
                      <center><button class="btn btn-primary">Send</button></center>
                      </div>                  
                    </div>
                </div>
              <% end%>            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<style type="text/css">
  input[type="file"] {
    display: none;
}
@media screen and (-webkit-min-device-pixel-ratio:0) {
  .thumbnail {
  /*margin-top: -21px;*/
  margin-left: 4px;
  float: left;
  height: 74px;
  width: 77px;
  }
}
.uploaded-photo {
  margin-top: 7px;
  }
</style>

<script type="text/javascript">
  setTimeout(function(){

  if(window.File && window.FileList && window.FileReader)
    {
    var filesInput = document.getElementById("files");
    filesInput.addEventListener("change", function(event){
    var files = event.target.files; //FileList object
    var output = document.getElementById("result");
    for(var i = 0; i< files.length; i++)
      {
        var sep = '&&&=>'
        document.getElementById('fileDragName').value = document.getElementById('fileDragName').value + sep + files[i].name
        document.getElementById('fileDragSize').value =  document.getElementById('fileDragSize').value + sep + files[i].size
        document.getElementById('fileDragType').value = document.getElementById('fileDragType').value + sep + files[i].type
          reader = new FileReader();
          reader.onload = function(event) {
          document.getElementById('fileDragData').value =  document.getElementById('fileDragData').value+sep+ event.target.result;}
          reader.readAsDataURL(files[i]);
        var file = files[i];
        //Only pics
        if(!file.type.match('image'))
          continue;
        var picReader = new FileReader();
        picReader.addEventListener("load",function(event){
        var picFile = event.target;
        var div = document.createElement("div");  
        div.innerHTML = "<img class='thumbnail' src='" + picFile.result + "'" +
                "title='" + picFile.name + "'/>";                    
        output.insertBefore(div,null);   
        });
         //Read the image
        picReader.readAsDataURL(file);
      }                               
       
    });
    }
    else
    {
     console.log("Your browser does not support File API");
    }

  },1000);  
</script>

app/views/claims/edit.html.erb
<h1>Editing Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

app/views/claims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Claims</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.user_id %></td>
        <td><%= claim.title %></td>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

app/views/claims/new.html.erb
<%= render 'form' %>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @claim.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @claim.title %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>

app/views/home/index.html.erb
<%= link_to "New Claim", new_claim_path, class: "btn btn-primary" %>
<br><br>
<%@attachments.each do |attach|%>
	<%= image_tag attach.file, style: "{width: 77px; height:74px; }"%>
<%end%>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
<div class="<%= flash_class(key) %> fade in">
  <a href="#" data-dismiss="alert" class="close">×</a>
  <%= value %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
	<p class="text-muted">Place sticky footer content here.</p>
	</div>
	</footer>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ClaimPhotos</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class=""><a href="/">Home</a></li>    			               
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li><%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
         </li>
        <% else %>
         <li> <%= link_to "Sign up", new_user_registration_path %></li>
         <li> <%= link_to "sign in", new_user_session_path %></li>
        <% end %> 
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CombiledRnv</title>
    <%= csrf_meta_tags %>
        <meta name='viewport' content='width=device-width, maximum-scale=1.0, minimum-scale=1.0, initial-scale=1.0' />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="main-body container">
    	<%= render 'layouts/flash_messages' %>    
    <%= yield %>
    </div>
    <%= render "layouts/footer"%>    
  </body>
</html>